# 微信相关设置
wechat:
  token: 12301230
  # 是否获取微信公众平台的ip白名单(用于防止doss检测)
  ip_detection: false
  # 如果上面的选项为true，下面两项内容必填；如要开启后面文本转语音服务，下面两项内容必填
  appid: "****"
  secret: "****"

# openai相关设置
openai:
  #填写openai的api_keys时，要注意前面要加上：Bearer, 可以填写多个,因为单个账号有速率的限制
  api_keys:   # ！需要改写这个
   # - "Bearer sk-****"
   # - "Bearer sk-****"
  # 单条消息的长度，这个参数对回复速度有非常大的影响，请不要填太大~
  max_tokens: 80
  # 是否开启流式响应
  stream_response: true
  # 模型
  model: "gpt-3.5-turbo"
  # temperature，越大随机性越强
  temperature: 0.8
  # 有时候文本长度超过150，用该参数限制长度避免超过微信能发送的最长消息
  rsize: 500
  # 对话的保存历史
  save_history: 21
  
# azure文本转语音设置
azure:
  # 是否开启文本转语音服务
  trans_to_voice: false
  # 如上面的选项为false，下面的内容不用填写
  # 新定义文本长度，开启后增加处理时间，避免文本太长，处理时间过久，超过15s
  max_token: 50
  # 密钥
  subscription: "****"
  region: "koreacentral"
  # 中文语音模型
  zh_model: "zh-CN-XiaoyanNeural"
  # 英文语音模型
  en_model: "en-US-AriaNeural"